# Generated by Django 5.0.4 on 2024-04-23 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp2023', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
