# Generated by Django 5.0.2 on 2024-04-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp2023', '0003_paymentrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentrequest',
            name='is_accepted',
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
